# Generated by Django 2.2.6 on 2019-10-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=60)),
                ('desp', models.TextField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('C', 'created'), ('P', 'inprocess'), ('D', 'done')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=60)),
                ('lname', models.CharField(max_length=60)),
            ],
        ),
    ]
